### ISSUE TITLE
adding docker file

### ISSUE THREAD

**Issue by rezakarbasi** [Desklop/RNNoise_Wrapper#13]
I think it'd be a good idea to add a docker integration feature to the repo.
Are you willing to do so? If yes, I can take its responsibility :)

**Comment by gongouveia** [comment]
@rezakarbasi Did you follow further this matter? That would be a nice addition

**Comment by rezakarbasi** [comment]
> @rezakarbasi Did you follow further this matter? That would be a nice addition

I did that for a personal project, I'll add the feature and make a pull request for that soon

**Comment by rezakarbasi** [comment]
@gongouveia I added the feature to my forked repo and asked the owner to pull the changes.
in the meantime you may use my forked repo: https://github.com/rezakarbasi/RNNoise_Wrapper

( I added a brief tutorial in the readme to setup the docker image )
